### ISSUE TITLE
FIP 140

### ISSUE THREAD

**Issue by bbhorrigan** [ryanries/ADReplStatus#10]
I work in Gov, I really love this tool. I do have a portion of my environment where I need to meet CMMC, which requires FIPs 140 which it looks like breaks your tool. Do you know if you ever plan on making that work in environments that have to keep that off for security concerns?

**Comment by ryanries** [comment]
Are you referring to the original version of ADReplStatus, or the new version you got from this Github repo?

I don't use any cryptography in the app at all, so I would be surprised that FIPS broke it.

But on the other hand I wouldn't be _that_ surprised, because FIPS ruins everything.

**Comment by ryanries** [comment]
@bbhorrigan  I just turned FIPS mode on in my lab and the app still seems to work fine.

**Comment by ryanries** [comment]
Closing as no repro
If you feel this was in error please let me know
Thanks

**Comment by bbhorrigan** [comment]
Hey sorry about that Ryan, I thought there was a note that it wasn't supported with FIPS, I'm testing it as well now as it looks like it works. Sorry for the confusion.
