### ISSUE TITLE
[Suggestion] ping, add choice between IPv4 and IPv6

### ISSUE THREAD

**Issue by barbarajoost** [ryanries/ADReplStatus#15]
I'm testing the tool today in our production environment. It's DC-Patch Day, so it's a good opportunity to see how it works.

For now, it works fine.

In our environment we have sometimes problems with the name resolution where it can be helpful to ping explicitly IPv4 or IPv6, like this:

ping servername -4
ping servername -6

It would be cool to have this choice in the tool too.

Barbara

**Comment by NikVanT** [comment]
@barbarajoost - Thanks for the suggestion. We can take this change. I'll update you when complete.

**Comment by NikVanT** [comment]
@ryanries - Thanks for the merge!

@barbarajoost - This functionality has been added. There should be a new release build available shortly.
