### ISSUE TITLE
Issue with the port tester

### ISSUE THREAD

**Issue by nightlink57070** [ryanries/ADReplStatus#17]
Hi, there is a problem with the port tester in version 1.3

when you select Kerberos it performs a test on port 53 (DNS)
when selecting DNS it performs a test on port 3268 (GC)
when GC is selected it performs a test on port 3269 (GC SSL)
when GC SSL is selected it performs a test on port 88 (Kerberos)

Can you have a look ?

Thanks,
Jonathan

**Comment by ryanries** [comment]
@nightlink57070 Thanks for letting us know, we will fix it. cc @NikVanT

**Comment by NikVanT** [comment]
@ryanries @nightlink57070 

Apologies for the delay. I'll have a fix shortly.

**Comment by ryanries** [comment]
Will have a new release build including this fix shortly
