### ISSUE TITLE
Support for .Net Framework 4.8.1

### ISSUE THREAD

**Issue by bbhorrigan** [ryanries/ADReplStatus#20]
Great job on the release today.

Do you know if there are any plans to support 4.8.1. ? I work in a very regulated environment that involves going thru a large amount of pain for an air gapped network, and the machine I generally run on has 4.8.1.

**Comment by bbhorrigan** [comment]
I guess I should also add, I run it right now on my machine that is 4.8.1 and it works fine.

**Comment by ryanriesMSFT** [comment]
@bbhorrigan So... you're good then? Not sure if you still need anything or not...

**Comment by bbhorrigan** [comment]
Yeah I'm good sorry about that. Works great on both versions.
